import os
import time

os.system("clear")
time.sleep(1)

print("\033[1;32;32m")
print("===========================================")
print("|  ADMIN-LOGIN   FINDER                   |")
print("|  Made by CyberAnt                       |")
print("===========================================")

print("[+]How to use?")
time.sleep(1)
print("[+]Enter www.targetsite.com And Try all finded pages")

target = input("[Enter] Site Target [+] ")
time.sleep(2)
os.system("clear")
time.sleep(2)

print("[+]Checking...")
os.system("clear")
time.sleep(1)
print("[+]Checking.")
os.system("clear")
time.sleep(1)
print("[+]Checking...")
os.system("clear")
time.sleep(1)
print("[+]Checking...")
os.system("clear")
time.sleep(1)
print("[+]Checking..")
os.system("clear")
time.sleep(1)
print("[+]Checking...")
os.system("clear")
time.sleep(1)
print("[+]Checking..")
os.system("clear")
time.sleep(1)
print("[+]Checking.")
os.system("clear")
time.sleep(1)

print("done")
time.sleep(4)
os.system("clear")

print("[+] Finding " + target + "Admin-login page [+]")
time.sleep(4)


#target
#ex print(target + "/" + "t")
print(target + "admin.php " + " Try This")
time.sleep(2)
print(target + "index.php " + " Try This")
time.sleep(2)
print(target + "login.php " + " Try This")
time.sleep(2)
print(target + "login.html " + " Try This")
time.sleep(2)
print(target + "administrator " + " Try This")
time.sleep(2)
print(target + "admin " + " Try This")
time.sleep(2)
print(target + "adminpanel " + " Try This")
time.sleep(2)
print(target + "cpanel " + " Try This")
time.sleep(2)
print(target + "login " + " Try This")
time.sleep(2)
print(target + "wp-login.php " + " Try This")
time.sleep(2)
print(target + "administrator " + " Try This")
time.sleep(2)
print(target + "admins " + " Try This")
time.sleep(2)
print(target + "logins " + " Try This")
time.sleep(2)
print(target + "admin.asp " + " Try This")
time.sleep(2)
print(target + "login.asp " + " Try This")
time.sleep(2)
print(target + "adm/ " + " Try This")
time.sleep(2)
print(target + "admin/ " + " Try This")
time.sleep(2)
print(target + "admin/account.html " + " Try This")
time.sleep(2)
print(target + "admin/login.html " + " Try This")
time.sleep(2)
print(target + "admin.login.htm " + " Try This")
time.sleep(2)
print(target + "admin/controlpanel.html " + " Try This")
time.sleep(2)
print(target + "admin/controlpanel.htm " + " Try This")
time.sleep(2)
 
 
#second part admin finder

print("[!]Copy or screenshot the prev adminpanels text before this tool retry in 10seconds")
print("Dont exit")
time.sleep(10)

os.system("clear")

print("Starting..." + target)
time.sleep(4)


print(target + "admin/adminLogin.html " + " Try This")
time.sleep(2)
print(target + "admin/adminLogin.htm " + " Try This")
time.sleep(2)
print(target + "admin/admin.htm " + " Try This")
time.sleep(2)
print(target + "admin/admin.html " + " Try This")
time.sleep(2)
print(target + "admin/adminitem/ " + " Try This")
time.sleep(2)
print(target + "admin/adminitems/ " + " Try This")
time.sleep(1)
print(target + "administrator/ " + " Try This")
time.sleep(1)


os.system("clear")
time.sleep(1)

print("[+] 51 Admin-Panel Found  [+]")
time.sleep(1)
print("Thank you for Using our tool!")


